import {
  checksEffectsInteraction,
  thisLocal,
  txOrigin,
  gasCosts,
  blockTimestamp,
  lowLevelCalls,
  blockBlockhash,
  constantFunctions,
  similarVariableNames,
  inlineAssembly,
  noReturn,
  selfdestruct,
  guardConditions,
  deleteDynamicArrays,
  assignAndCompare,
  deleteFromDynamicArray,
  erc20Decimals,
  etherTransferInLoop,
  forLoopIteratesOverDynamicArray,
  intDivisionTruncate,
  stringBytesLength,
} from "@remix-project/remix-analyzer/src/solidity-analyzer/modules";

export const ANALYZER_RULES: { [rule: string]: any } = {
  txOrigin,
  gasCosts,
  thisLocal,
  checksEffectsInteraction,
  constantFunctions,
  similarVariableNames,
  inlineAssembly,
  blockTimestamp,
  lowLevelCalls,
  blockBlockhash,
  noReturn,
  selfdestruct,
  guardConditions,
  deleteDynamicArrays,
  assignAndCompare,
  erc20Decimals,
  stringBytesLength,
  intDivisionTruncate,
  etherTransferInLoop,
  deleteFromDynamicArray,
  forLoopIteratesOverDynamicArray,
};
